# Generated by Django 5.0 on 2023-12-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(editable=False, max_length=25, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=500)),
                ('linkedin', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('resume_1', models.CharField(max_length=50)),
                ('resume_2', models.CharField(max_length=50)),
                ('resume_3', models.CharField(max_length=50)),
            ],
        ),
    ]
