# Generated by Django 5.0 on 2023-12-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_about_alter_usermodel_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='resume_1',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='resume_2',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='resume_3',
        ),
    ]
