# Generated by Django 5.0 on 2023-12-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_uploadresume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadResume',
        ),
    ]
