# Generated by Django 5.0 on 2023-12-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_usermodel_resume_1_remove_usermodel_resume_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='avatar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='about',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='bio',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
