# Generated by Django 5.0 on 2023-12-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_uploadresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='about',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
