# Generated by Django 5.0 on 2023-12-20 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermodel_avatar_alter_usermodel_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='uid',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestid', models.CharField(editable=False, max_length=50, unique=True)),
                ('requestmessage', models.CharField(max_length=5000, null=True)),
                ('requestfrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_from', to='users.usermodel')),
                ('requestto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_to', to='users.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responseid', models.CharField(editable=False, max_length=50, unique=True)),
                ('responsemessage', models.CharField(max_length=5000)),
                ('responsefrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_from', to='users.usermodel')),
                ('responseto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_to', to='users.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumeid', models.CharField(editable=False, max_length=50, unique=True)),
                ('resumename', models.CharField(max_length=100, null=True)),
                ('resumelink', models.CharField(editable=False, max_length=250, unique=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
            ],
        ),
    ]
