# Generated by Django 5.0 on 2023-12-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usermodel_email_alter_usermodel_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsemodel',
            name='responsefrom',
        ),
        migrations.RemoveField(
            model_name='responsemodel',
            name='responseto',
        ),
        migrations.RemoveField(
            model_name='resumemodel',
            name='userid',
        ),
        migrations.DeleteModel(
            name='RequestModel',
        ),
        migrations.DeleteModel(
            name='ResponseModel',
        ),
        migrations.DeleteModel(
            name='ResumeModel',
        ),
    ]
