# Generated by Django 5.0 on 2023-12-20 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
        ('users', '0006_remove_responsemodel_responsefrom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responseid', models.CharField(editable=False, max_length=50, unique=True)),
                ('responsemessage', models.CharField(max_length=5000)),
                ('responsefrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_from', to='users.usermodel')),
                ('responseto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_to', to='users.usermodel')),
                ('resumeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_for_resume', to='resume.resumemodel')),
            ],
        ),
    ]
