# Generated by Django 5.0 on 2023-12-22 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestid', models.CharField(editable=False, max_length=100, unique=True)),
                ('userid', models.CharField(max_length=100)),
                ('resumelink', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=2500)),
                ('requestedat', models.DateField(default=datetime.date.today)),
                ('responded', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responseid', models.CharField(editable=False, max_length=50, unique=True)),
                ('requestid', models.CharField(editable=False, max_length=50, unique=True)),
                ('fromuserid', models.CharField(editable=False, max_length=50)),
                ('responsemessage', models.CharField(max_length=5000)),
            ],
        ),
    ]
