# Generated by Django 5.0 on 2023-12-21 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestid', models.CharField(editable=False, max_length=100, unique=True)),
                ('userid', models.CharField(max_length=100)),
                ('resumelink', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=1000)),
                ('requestedat', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
