# Generated by Django 5.0 on 2023-12-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='avatar',
            field=models.CharField(default='https://lh3.googleusercontent.com/a/ACg8ocJ-WWqNiQv0BppwWISN_SyIT6Xk3pPNVefijlfE7Hbc=s96-c', max_length=250),
        ),
    ]
