# Generated by Django 5.0 on 2023-12-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsemodel',
            name='resumelink',
        ),
    ]
