# Generated by Django 5.0 on 2023-12-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_requestmodel_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='file',
            field=models.FileField(null=True, upload_to='resume/'),
        ),
    ]
