# Generated by Django 5.0 on 2023-12-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_requestmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmodel',
            name='file',
        ),
    ]
