# Generated by Django 5.0 on 2023-12-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_alter_requestmodel_resumelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='avatar',
            field=models.CharField(max_length=250),
        ),
    ]
