# Generated by Django 5.0 on 2023-12-20 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_remove_responsemodel_responsefrom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumeid', models.CharField(editable=False, max_length=50, unique=True)),
                ('resumename', models.CharField(max_length=100, null=True)),
                ('resumelink', models.CharField(editable=False, max_length=250, unique=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
            ],
        ),
    ]
